Repository HSE-algo-23-crow/manual_tasks, pull requests merged in 2023-09, with the labels that each got.

#2 Citrine task 0
  task_0/task.md
Labels: citrine

#5 Gigacode task 0
  task_0/images.jpg
  task_0/task.md
Labels: gigacode

#6 Yes_task_0
  task_0/task.md
Labels: ✅ yes
